//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public int id_cuenta { get; set; }
        public string titular { get; set; }
        public string tipo_cuenta { get; set; }
        public string dui { get; set; }
        public double saldo { get; set; }
    }
}
