//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public cargo()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_cargo { get; set; }
        public string nombre_cargo { get; set; }
        public int horas_laborales { get; set; }
        public string descripcion { get; set; }
        public double salario { get; set; }
    
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
