//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public int id_compra { get; set; }
        public int id_stock { get; set; }
        public int id_proveedor { get; set; }
        public double cantidad { get; set; }
        public double precio_compra { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual stock stock { get; set; }
    }
}
