//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModel : DbContext
    {
        public DbModel()
            : base("name=DbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<balance> balance { get; set; }
        public DbSet<cargo> cargo { get; set; }
        public DbSet<compra> compra { get; set; }
        public DbSet<deposito_empleado> deposito_empleado { get; set; }
        public DbSet<detalle_orden> detalle_orden { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<orden> orden { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<stock> stock { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
