//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposito_empleado
    {
        public int id_deposito { get; set; }
        public int id_empleado { get; set; }
        public Nullable<System.DateTime> fecha_pagado { get; set; }
        public Nullable<double> propina_mes { get; set; }
        public Nullable<double> salario_mes { get; set; }
        public Nullable<double> total_mes { get; set; }
        public Nullable<double> total_acumulado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
