//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detalle_orden
    {
        [Display(Name = "#")]
        public int id_detalle { get; set; }
        [Display(Name = "#orden")]
        public int id_orden { get; set; }
        [Display(Name = "#producto")]
        public int id_producto { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }

    
        public virtual orden orden { get; set; }
        public virtual producto producto { get; set; }
    }
}
