//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.deposito_empleado = new HashSet<deposito_empleado>();
            this.orden = new HashSet<orden>();
        }
    
        public int id_empleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string dui { get; set; }
        public Nullable<int> id_cargo { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual ICollection<deposito_empleado> deposito_empleado { get; set; }
        public virtual ICollection<orden> orden { get; set; }
    }
}
