//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public orden()
        {
            this.detalle_orden = new HashSet<detalle_orden>();
        }
    
        public int id_orden { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public int n_mesa { get; set; }
        public string estado { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> propina { get; set; }
    
        public virtual ICollection<detalle_orden> detalle_orden { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
