//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public stock()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int id_stock { get; set; }
        public string nombre_ingrediente { get; set; }
        public double cantidad { get; set; }
    
        public virtual ICollection<compra> compra { get; set; }
    }
}
